<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
				<br/>
				<i class="icon-credit-card icon-7x"></i>
                                <input type="hidden" id="hidden_image_type" value=""/>
                                <input type="hidden" id="hidden_image_id" value=""/>
                                <h4 id="myModalLabel" class="semi-bold">Are you sure you want to delete ?</h4>
				<br/>
			</div>
			<div class="modal-footer">
				<a href="#" class="deletelink btn btn-danger">Delete</a>
				<a href="#" data-dismiss="modal" class="btn btn-default">Cancel</a>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>