<?php $this->headScript()->appendFile($this->ADMIN_PATH . "js/user.js"); ?>
<div id="user-listing"></div>
<!--main content start-->
      <section id="main-content">
          <section class="wrapper">
              <!-- page start-->
              <div class="row">
                  <?php echo $this->partial('partial/userprofile.phtml', array('config' => $this)); ?>
                  <aside class="profile-info col-lg-9">
                      <section class="panel">
                         
                          <footer class="panel-footer">
                             
                          </footer>
                      </section>
                      <section class="panel">
                          <div class="panel-body bio-graph-info">
                              <h1>Bio Graph</h1>
                              <div class="row">
                                  <div class="bio-row">
                                      <p><span>Name </span>: <?php echo $this->useralldata['usr_name']; ?></p>
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Email</span>: <?php echo $this->useralldata['lgn_email']; ?></p>
									 
                                  </div>
                                  <div class="bio-row">
                                      <p><span>Gender </span>:&nbsp;&nbsp 
								<?php if ($this->useralldata["usr_gender"] == 0): ?>
									<span class="label label-primary label-mini">Female</span>
								<?php endif; ?>
								<?php if ($this->useralldata["usr_gender"] == 1): ?>
									<span class="label label-danger label-mini">Male</span>
								<?php endif; ?></p>
                                  </div>
								  <div class="bio-row">
								
                                   <button class="btn btn-danger pull-left"><a href="<?php echo $this->url(array("module" => "admin", "controller" => "user", "action" => "userpost", "usr_id" => $this->useralldata['usr_id']), null, true); ?>">User Post List</a></button>
								   </div>
								   
                              </div>
							  
                          </div>
                      </section>
                     
                  </aside>
              </div>

              <!-- page end-->
          </section>
      </section>
      <!--main content end-->

<!-- Modal -->
<div class="modal fade" id="update_status_Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <br/>
                <i class="icon-credit-card icon-7x"></i>
                <input type="hidden" id="hidden_image_type" value=""/>
                <input type="hidden" id="hidden_image_id" value=""/>
                <h4 id="myModalLabel" class="semi-bold add_status"></h4>
                <br/>
            </div>
            <div class="modal-footer">
                <a href="#" class="update_status_link btn btn-danger">submit</a>
                <a href="#" data-dismiss="modal" class="btn btn-default">Cancel</a>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>