<?php $this->headScript()->appendFile($this->ADMIN_PATH . "js/cms.js"); ?>
<?php $this->headScript()->appendFile($this->BASE_URL . "library/ckeditor/ckeditor.js"); ?>
<?php $this->headScript()->appendFile($this->BASE_URL . "library/ckeditor/adapters/jquery.js");
?>
<div id="cms-listing"></div>
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                <?php echo $this->flashmessages(); ?>
                <?php if (count($this->errorMessage) > 0): ?>
                    <div class="col-lg-12">                  
                        <div class="alert alert-block alert-danger fade in">
                            <button type="button" class="close close-sm" data-dismiss="alert">
                                <i class="fa fa-times"></i>
                            </button>
                            <?php foreach ($this->errorMessage as $erroValue): ?>
                                <?php echo $erroValue; ?><br/>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <form action="" method="post" id="cmslistingform">
                    <section class="panel">
                        <header class="panel-heading">
                            Cms Listing

                            <?php if (count($this->cmssData) > 0): ?> 
                                <div class="delete_All pull-right">    
                                    &nbsp;&nbsp;<input type="submit" accesskey="s" value="Delete All" name="multiaction"  id="multiaction" class="btn btn-sm btn-danger delete_all"/>      
                                </div>
                            <?php else: ?>
                                &nbsp;
                            <?php endif; ?>

                            <!--<a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url(array("module" => "admin", 'controller' => 'cms', 'action' => 'form'), null, TRUE); ?>">&nbsp;+ Add</a>-->

                            <div class="form-group col-sm-12 padding_left_0 padding_top_20">

                                <div class="col-sm-2 padding_left_0 padding_right_0">
                                    <input type="text" class="form-control" name="searchtype" value="<?php echo $this->searchtype ?>" >
                                </div>
                                <div class="col-sm-2">
                                    <input class="btn btn-success" id="button-submit" type="submit" value="Search" />
                                    <a class="btn btn-success" href="<?php echo $this->url(array("module" => "admin", 'controller' => 'cms', 'action' => 'unsetsession', 'pagename' => 'list'), null, TRUE); ?>">Clear</a>
                                </div>
                            </div>

                        </header>

                        <table class="table table-striped table-advance table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        <input id="selectall" type="checkbox"/>
                                        <a href="<?php echo $this->url(array('controller' => 'cms', 'action' => 'list', 'field' => 'c_title', 'sort' => 'asc', 'module' => 'admin'), 'default', false); ?>">
                                            <img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_asc.png"  alt="Ascending" title="Ascending" class="sort_asc" />
                                        </a>
                                        <i class="fa fa-list-alt"></i> Title
                                        <a href="<?php echo $this->url(array('controller' => 'cms', 'action' => 'list', 'field' => 'c_title', 'sort' => 'desc', 'module' => 'admin'), 'default', false); ?>">
                                            <img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_desc.png"  alt="Descending" title="Descending" class="sort_desc"  />
                                        </a>
                                    </th>
                                    <th>
                                        <a href="<?php echo $this->url(array('controller' => 'cms', 'action' => 'list', 'field' => 'c_createddate', 'sort' => 'asc', 'module' => 'admin'), 'default', false); ?>">
                                            <img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_asc.png"  alt="Ascending" title="Ascending" class="sort_asc" />
                                        </a>
                                        <i class="fa fa-clock-o"></i> Created Date
                                        <a href="<?php echo $this->url(array('controller' => 'cms', 'action' => 'list', 'field' => 'c_createddate', 'sort' => 'desc', 'module' => 'admin'), 'default', false); ?>">
                                            <img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_desc.png"  alt="Descending" title="Descending" class="sort_desc"  />
                                        </a>
                                    </th>
                                    <th>
                                        <a href="<?php echo $this->url(array('controller' => 'cms', 'action' => 'list', 'field' => 'c_status', 'sort' => 'asc', 'module' => 'admin'), 'default', false); ?>">
                                            <img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_asc.png"  alt="Ascending" title="Ascending" class="sort_asc" />
                                        </a>
                                        <i class="fa fa-check-square-o"></i> Status
                                        <a href="<?php echo $this->url(array('controller' => 'cms', 'action' => 'list', 'field' => 'c_status', 'sort' => 'desc', 'module' => 'admin'), 'default', false); ?>">
                                            <img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_desc.png"  alt="Descending" title="Descending" class="sort_desc"  />
                                        </a>
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (count($this->cmssData) > 0): ?>
                                    <?php foreach ($this->cmssData as $key => $value) : ?>
                                        <tr>
                                            <td>
                                                <input type="checkbox" class="content-checkbox chek_all" name="multicheck[]" value="<?php echo $value["c_id"]; ?>"/>&nbsp;
                                               <a href="<?php echo $this->url(array("module" => "admin", "controller" => "cms", "action" => "form", "c_id" => $value["c_id"]), null, true); ?>"><?php echo $value["c_title"]; ?></a>
                                            </td>
                                            <td>
                                                <?php echo date($this->DATE_FORMATE, strtotime($value["c_createddate"])); ?>

                                            </td>
                                            <td>
												<?php 
													if($value["c_status"] == 1){	
														$c_status = 'InActive';
													} else {
														$c_status = 'Active';
													}
												?>
                                                <a href="#" class="myLink" c_status="<?php echo $c_status; ?>" href_link="<?php echo $this->url(array("module" => "admin", "controller" => "cms", "action" => "changestatus", "c_status" => $value["c_status"], "c_id" => $value["c_id"]), null, true); ?>">
                                                    <?php if ($value["c_status"] == 1): ?>
                                                        <span class="label label-success label-mini">Active</span>
                                                    <?php else: ?>
                                                        <span class="label label-warning label-mini">InActive</span>
                                                    <?php endif; ?>
                                                </a>
                                            </td>
                                            <td>
                                                <a href="<?php echo $this->url(array("module" => "admin", "controller" => "cms", "action" => "form", "c_id" => $value["c_id"]), null, true); ?>" title="Edit" class="btn btn-primary btn-xs">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <a href="#" title="Delete" class="btn btn-danger btn-xs deletemodal" target_href="<?php echo $this->url(array("module" => "admin", "controller" => "cms", "action" => "delete", "c_id" => $value["c_id"]), null, true); ?>">
                                                    <i class="fa fa-trash-o"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr class="row2" >
                                        <td>&nbsp;</td>
                                        <td colspan="8"> No Record Found</td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>

                        <div class="panel-body">
                            <div>
                                <?php
                                if (count($this->cmssData) > 0):
                                    echo $this->paginator->displayPages();
                                endif;
                                ?>
                            </div>
                        </div>				  
                    </section>	
                </form>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Modal -->
<div class="modal fade" id="update_status_Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
				<br/>
				<i class="icon-credit-card icon-7x"></i>
				<input type="hidden" id="hidden_image_type" value=""/>
				<input type="hidden" id="hidden_image_id" value=""/>
				<h4 id="myModalLabel" class="semi-bold add_status"></h4>
				<br/>
			</div>
			<div class="modal-footer">
				<a href="#" class="update_status_link btn btn-danger">submit</a>
				<a href="#" data-dismiss="modal" class="btn btn-default">Cancel</a>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
<!-- /.modal-dialog -->
</div>