<div class="banner-div">
    <div class="hero-div clearfix"></div><!-- end of hero div -->
        <div class="caption">
		<h2>Approved/Rejected Post.</h2><br>
            <a href="<?php echo $this->BASE_URL . 'index/approvepost/post_id/' . base64_encode($this->post_id) ; ?>">Approve</a> &nbsp; &nbsp;   
			<a href="<?php echo $this->BASE_URL . 'index/rejectpost/post_id/' . base64_encode($this->post_id) ; ?>">Reject</a>             
        </div>
</div><!-- end of banner div -->

