<div class="container-area">
     	
        <div class="container" id="howitworks">
			<div class="row">      
				<div class="howitwork-container clearfix">
					<h2>Post has been Rejected.</h2>
					<div class="activate_img">
					 <img src="<?php echo $this->FRONT_IMAGE_PATH;?>right.png" alt="Thank You" />
					 </div>
					 
			
				</div><!-- end of howitwork-container -->
            </div><!-- end of row -->        
        </div><!-- end of container -->
</div>