<script>
    var LATITUDE = '<?php echo $this->LATITUDE; ?>';
    var LONGITUDE = '<?php echo $this->LONGITUDE; ?>';
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyX0wkcIej0ekCUACWqem9xcUEaES0y1M"></script>
<?php $this->headScript()->appendFile($this->ADMIN_PATH . "js/post.js"); ?>
<div id="post-listing"></div>
<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <!-- page start-->
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
						<?php if ($this->successmessage != ""): ?>
							<div class="alert alert-success">
								<i class="icon-ok-sign"></i> 
								<?php echo $this->successmessage; ?>
							</div>
						<?php endif; ?>
						<?php if (count($this->errorMessageArray) > 0): ?>
							<div class="col-lg-12">                  
								<div class="alert alert-block alert-danger fade in">
									<button type="button" class="close close-sm" data-dismiss="alert">
										<i class="fa fa-times"></i>
									</button>
									<?php foreach ($this->errorMessageArray as $erroValue): ?>
										<?php echo $erroValue; ?><br/>
									<?php endforeach; ?>
								</div>
							</div>
						<?php endif; ?>
						<header class="panel-heading"><?php echo $this->mode; ?> Post
							<a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "list"), null, TRUE); ?>">&nbsp;All Post</a>
						</header>
							<div class="panel-body">
								<form role="form"  id="post-form" name="post-form"  enctype="multipart/form-data"  action="" method="post">
								<div class="form-horizontal tasi-form" >
									<div class="form-group">
										<div class="col-sm-3">
											
											<?php if($this->mode == 'Add'): ?>
											<label><span class="error-star">*</span>Image </label><br/>
											<input type="file" class="file-pos" id="cat_image" name="cat_image">
											<?php endif; ?>
											<?php $src_path_image = $this->PUBLIC_PATH . "upload/post/" . $this->imageName; 
												  $src_path_video = $this->PUBLIC_PATH . "upload/post/" . $this->post_video;
											?>
												
											<?php if ($this->imageName != ""): ?>
												
												<?php if($this->post_video!=''){
													?>
													<label><span class="error-star">*</span>Video</label><br/>
													
													<a href="<?php echo $src_path_video; ?>" target="_blank"><img src="<?php echo $src_path_image; ?>" style="height:200px;width:200px;"/></a>
													
													
												<?php } else {
													?>
													<label><span class="error-star">*</span>Image </label><br/>
													<a href="<?php echo $src_path_image; ?>" target="_blank"><img src="<?php echo $src_path_image; ?>" style="height:200px;width:200px;"/></a>
												<?php }?>
												
												
											<?php endif;  ?>
										</div>
										
									</div>
									<div class="form-group">
										<div class="col-sm-4">
											<label><span class="error-star">*</span>Title</label>
											<?php echo $this->form->post_title; ?>
										</div>
										<div class="col-sm-4">
											<label><span class="error-star">*</span>Category</label>
											<?php echo $this->form->post_cat_id; ?>
										</div>
										<div class="col-sm-4">
											<label><span class="error-star">*</span>Type</label><br>
											<input id="post_type" type="radio" name="post_type" <?php if ($this->post_type == 1): echo 'checked'; endif; ?> value="1"> &nbsp; Good &nbsp;&nbsp;&nbsp;
											<input id="post_type" type="radio" name="post_type" <?php if ($this->post_type == 2): echo 'checked'; endif; ?> value="2"> &nbsp; Bad
										</div>
									</div>
									<div class="form-group">	 
										<div class="col-sm-4">
											<label><span class="error-star">*</span>Description</label>
											<?php echo $this->form->post_desc; ?>
										</div>
									</div>
									<div class="form-group col-sm-12">
                                        <div class="col-sm-4">
                                            <label><span class="error-star">*</span>Location</label>
											<?php echo $this->form->post_location; ?>
                                        </div>
                                        <div class="col-sm-6">
                                            <label>&nbsp;</label>

                                            <br/>
                                            <input type="button" id="search-map" class="btn btn_map_search" value="Search" />
                                            <input type="button" id="current-location" class="btn btn-success" value="Current Location" />
                                        </div>
                                    </div>
                                    <div style="clear:both"></div>

                                    <div class="form-group col-sm-12">
                                        <div class="col-sm-6">
                                            <div id="map-canvas" class="gmaps"></div>
                                        </div>
                                    </div>
									<div class="form-group col-sm-12">
                                        <div class="col-sm-3">
											<?php echo $this->form->post_lattitude; ?>
                                        </div>
                                        <div class="col-sm-3">
                                            <?php echo $this->form->post_longitude; ?>
                                        </div>
                                    </div>
									<div class="form-group">	 
										<div class="col-sm-4">
											<label><span class="error-star">*</span>Status</label>
											<?php echo $this->form->post_status; ?>
										</div>
										<div class="col-sm-4">
											<label><span class="error-star">*</span> Approved/Rejected Status</label>
											<?php echo $this->form->post_approve_status; ?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label"></label>
										<div class="col-lg-12 center_button">
											<button class="btn btn-success" type="submit">
												<?php if($this->mode == 'Add'): ?>Save
												<?php else: ?>Update<?php endif; ?>
											</button>
											<a href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "list"), null, TRUE); ?>" class="btn btn-danger cancelbutton">Cancel</a>
										</div>
									</div>
								</div>
							</section>
						</form>
					</div>
				</div>
				<!-- page end-->
			</div>
		</section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->