<div id="post-viewing"></div>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.0/jquery.min.js'></script>
<?php $this->headScript()->appendFile($this->ADMIN_PATH . "js/postview.js"); ?>
<?php $post_model = $this->postalldata; ?>
      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">
              <!-- page start-->
              <div class="row">
                  <div class="col-sm-6">
                      <section class="panel">
                          <header class="panel-heading">
                              Basic Table
                          </header>
                          <table class="table">
                              <thead>
                              <tr>
                                  <th>#</th>
                                  <th>First Name</th>
                                  <th>Last Name</th>
                                  <th>Username</th>
                              </tr>
                              </thead>
                              <tbody>
                              <tr>
                                  <td>1</td>
                                  <td>Mark</td>
                                  <td>Otto</td>
                                  <td>@mdo</td>
                              </tr>
                              <tr>
                                  <td>2</td>
                                  <td>Jacob</td>
                                  <td>Thornton</td>
                                  <td>@fat</td>
                              </tr>
                              <tr>
                                  <td>3</td>
                                  <td>Larry</td>
                                  <td>the Bird</td>
                                  <td>@twitter</td>
                              </tr>
                              </tbody>
                          </table>
                      </section>
                  </div>
                  <div class="col-sm-6">
                      <section class="panel">
                          <header class="panel-heading">
                              Striped Table
                          </header>
                          <table class="table table-striped">
                              <thead>
                              <tr>
                                  <th>#</th>
                                  <th>First Name</th>
                                  <th>Last Name</th>
                                  <th>Username</th>
                              </tr>
                              </thead>
                              <tbody>
                              <tr>
                                  <td>1</td>
                                  <td>Mark</td>
                                  <td>Otto</td>
                                  <td>@mdo</td>
                              </tr>
                              <tr>
                                  <td>2</td>
                                  <td>Jacob</td>
                                  <td>Thornton</td>
                                  <td>@fat</td>
                              </tr>
                              <tr>
                                  <td>3</td>
                                  <td>Larry</td>
                                  <td>the Bird</td>
                                  <td>@twitter</td>
                              </tr>
                              </tbody>
                          </table>
                      </section>
                  </div>
              </div>
             
              <div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                              Advanced Table
                          </header>
                          <table class="table table-striped table-advance table-hover">
                              <thead>
                              <tr>
                                  <th><i class="fa fa-bullhorn"></i> Company</th>
                                  <th class="hidden-phone"><i class="fa fa-question-circle"></i> Descrition</th>
                                  <th><i class="fa fa-bookmark"></i> Profit</th>
                                  <th><i class=" fa fa-edit"></i> Status</th>
                                  <th></th>
                              </tr>
                              </thead>
                              <tbody>
                              <tr>
                                  <td><a href="#">Vector Ltd</a></td>
                                  <td class="hidden-phone">Lorem Ipsum dorolo imit</td>
                                  <td>12120.00$ </td>
                                  <td><span class="label label-info label-mini">Due</span></td>
                                  <td>
                                      <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
                                      <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
                                      <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
                                  </td>
                              </tr>
                              
                              </tbody>
                          </table>
                      </section>
                  </div>
				  <div class="col-sm-6">
                      <section class="panel">                        
                          <table class="table table-striped">
                              <thead>
                              <tr>
                                  <th>#</th>
                                  <th>First Name</th>
                                  <th>Last Name</th>
                                  <th>Username</th>
                              </tr>
                              </thead>
                              <tbody>
                              <tr>
                                  <td>1</td>
                                  <td>Mark</td>
                                  <td>Otto</td>
                                  <td>@mdo</td>
                              </tr>
                              
                              </tbody>
                          </table>
                      </section>
                  </div>
              </div>
              <!-- page end-->
          </section>
      </section>
      <!--main content end-->
<section id="main-content">
    <section class="wrapper">
		<a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "list"), null, TRUE); ?>">&nbsp;Back</a>
        <a class="btn btn-success btn-sm pull-right edit_space" href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "form","post_id" => $post_model['post_id']), null, TRUE); ?>">&nbsp;Edit</a><br/><br/>
		<!-- page start-->
        <div class="row">
			<div class="col-md-12">
                <section class="panel">
                    <div class="panel-body">
                        <div class="col-md-3">
                            <div class="pro-img-details">
								<?php 
									$image = '';
									if ($post_model['post_image'] != '') {
										$main_image = $this->ROOT_PATH . "post/" . $post_model['post_image'];
										if (file_exists($main_image)) {
											$image = $this->PUBLIC_PATH . "upload/post/" . $post_model['post_image'];
										} else {
											$image = $this->FRONT_IMAGE_PATH . "comingsoon.jpg";
										}
									} else {
										$image = $this->FRONT_IMAGE_PATH . "comingsoon.jpg";
									} 
									$src_path_video = $this->PUBLIC_PATH . "upload/post/" . $post_model['post_video']; 
								?>
								
								<?php if($post_model['post_video']!=''){
								?>
									<a href="<?php echo $src_path_video; ?>" target="_blank"><img src="<?php echo $image; ?>"/></a>
								<?php } else { ?>
									<a href="<?php echo $image; ?>" target="_blank"><img src="<?php echo $image; ?>"></a>
								<?php }?>
												
								
                            </div>
                        </div>
                        <div class="col-md-3">
							<h4 class="pro-d-title">
							  <a href="#" class="">
								  <?php echo ucfirst($post_model['post_title']); ?>
							  </a>
							</h4>
							<p>
								<?php echo $post_model['post_desc']; ?>
							</p>
						</div>
						<div class="col-md-3">
                            <div class="product_meta">
								<span class="posted_in"> <strong>Location :</strong>&nbsp;<?php echo ucfirst($post_model['post_location']); ?></span>
								<span class="posted_in"> <strong>Lattitude :</strong>&nbsp;<?php echo ucfirst($post_model['post_lattitude']); ?></span>
								<span class="posted_in"> <strong>Longitude :</strong>&nbsp;<?php echo ucfirst($post_model['post_longitude']); ?></span>
								<span class="posted_in"> <strong>User :</strong>&nbsp;<?php echo ucfirst($post_model['usr_name']); ?></span>
								<span class="posted_in"> <strong>Category :</strong>&nbsp;<?php echo ucfirst($post_model['cat_name']); ?></span>
								<span class="posted_in"> <strong>Type :</strong>&nbsp;
									<?php if ($post_model["post_type"] == 1): ?>
										<div class="label label-success">Good</div>
									<?php else: ?>
										<div class="label label-danger">Bad</div>
									<?php endif; ?>
								</span>
								<span class="posted_in"> <strong>Post Approved/Rejected Status :</strong>&nbsp;
									<?php if ($post_model["post_approve_status"] == 1){ ?>
										<div class="label label-success">Approved</div>
									<?php } else if ($post_model["post_approve_status"] == 2){ ?>
										<div class="label label-danger">Rejected</div>
									<?php }else { ?>
										<div class="label label-warning">Pending</div>										
									<?php } ?>
								</span>
							</div>
						</div>
						<div class="col-md-3">
                            <div class="product_meta">
								<span class="posted_in"> <strong>Created Date :</strong>&nbsp;<?php echo date($this->DATE_FORMATE, strtotime($post_model['post_createddate'])); ?></span>
								<span class="posted_in"> <strong>Updated Date :</strong>&nbsp;<?php echo date($this->DATE_FORMATE, strtotime($post_model['post_updateddate'])); ?></span>
								<span class="posted_in"> <strong>Status :</strong>&nbsp;
									<?php if ($post_model["post_status"] == 1): ?>
										<div class="label label-success">Active</div>
									<?php else: ?>
										<div class="label label-warning">InActive</div>
									<?php endif; ?>
								</span>								
							</div>
						</div>
						<div class="col-md-3">
                            <div class="product_meta">
								<span class="posted_in"> <strong>Good Count :</strong>&nbsp;
									<div class="label label-success"><?php echo $this->PostlikegoodCount; ?></div>
								</span>
								<span class="posted_in"> <strong>Bad Count :</strong>&nbsp;
									<div class="label label-danger"><?php echo $this->PostlikebadCount; ?></div>
								</span>
							</div>
						</div>
					</div>
                </section>
				<section class="panel">
					<header class="panel-heading tab-bg-dark-navy-blue">
						<ul class="nav nav-tabs ">
							<li class="active">
								<a class="tab_view" data-toggle="tab" href="#comment"><b>Comment</b></a>
							</li>
						</ul>
					</header>
					<div class="panel-body">
						<div class="tab-content tasi-tab">
							<div id="comment" class="tab-pane active">
								<table class="table table-striped table-advance table-hover" style="border-collapse:collapse;">
									<thead>
										<tr>
											<th>&nbsp;</th>
											<th>&nbsp;</th>
											<th><i class="fa fa-user"></i> User Name</th>
											<th><i class="fa fa-comments"></i> Comments</th>
											<th><i class="fa fa-clock-o"></i> Date</th>
											<th>Action</th>
										</tr>
									</thead>
									<tbody>
									<?php 
										$gtlCommon = new GTL_Common();
										$i=1;
										$finalcount= count($this->finalArra);
										if($finalcount > 0){
											foreach($this->finalArra as $value) {
									?>
											<tr data-toggle="collapse" data-target="#demo<?php echo $i; ?>" class="accordion-toggle">
												<td>
													<img src="<?php echo $this->ADMIN_PATH; ?>/img/details_open.png">
												</td>
												<td>
													<?php echo $value['cmt_id']; ?>
												</td>
												<td>
													<a href="<?php echo $this->BASE_URL; ?>/admin/user/profile/usr_id/<?php echo $value['cmt_lgn_id']; ?>"><?php echo $value['usr_name']; ?></a>
												</td>
												<td>
													<?php echo $value['cmt_msg']; ?>
												</td>
												<?php $dateofpost =  $gtlCommon->time_elapsed_string($value['cmt_createddate']); ?>
												<td>
													<?php echo $dateofpost; ?>
												</td>
												<td>									
													<a href="#" title="Delete" class="btn btn-danger btn-xs deletemodal" target_href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "deletecomment", "cmt_id" => $value["cmt_id"]), null, true); ?>">
                                                    <i class="fa fa-trash-o"></i>
                                                </a>
												</td>
											</tr>
											<tr>
												<td colspan="6" class="hiddenRow">
													<div class="accordian-body collapse" id="demo<?php echo $i; ?>"> 
														<table class="table table-striped table-advance table-hover">
															<thead>
																<?php if($value['reply_count'] > 0){ ?>
																	<tr>
																		<th>&nbsp;</th>
																		<th><i class="fa fa-user"></i> User Name</th>
																		<th><i class="fa fa-comments"></i> Comment</th>
																		<th><i class="fa fa-clock-o"></i> Date</th>
																		<th>action</th>
																	</tr>
																	<?php foreach($this->commentreplyArray as $cmt){
																			foreach ($cmt as $rep){
																				if($rep['cmt_ref'] == $value['cmt_id']){
																				?>
																		
																				<tr>
																					
																					<td></td>
																					<td>
																						<a href="<?php echo $this->BASE_URL; ?>/admin/user/profile/usr_id/<?php echo $rep['cmt_lgn_id']; ?>"><?php echo $rep['usr_name']; ?></a>
																					</td>
																					<td>
																						<?php echo $rep['cmt_msg']; ?>
																					</td>
																					<?php $replyeofpost =  $gtlCommon->time_elapsed_string($rep['cmt_createddate']); ?>
																					<td>
																						<?php echo $replyeofpost; ?>
																					</td>
																					<td>
																					<a href="#" title="Delete" class="btn btn-danger btn-xs deletemodal" target_href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "deletecomment", "cmt_id" => $rep["cmt_id"]), null, true); ?>">
                                                    <i class="fa fa-trash-o"></i>
																					</td>
																					
																				</tr>
																
																				<?php }
																			}
																	} 
																} else { ?>
																	<tr>
																		<div class="no_comment_text">No Comment Reply</div>
																	</tr>
																<?php } ?>
															</thead>
														</table>
													</div> 
												</td>
											</tr>
											
											<?php $i++;} 
										} else{
										?>
										<tr>
										<td></td>
											<td>
											No Comment on this Post
											</td>
                                        </tr>
										<?php } ?>
									
									</tbody>
								</table>	
							</div>
						</div>
					</div>
				</section>
				
				
			</div>
        </div>
        <!-- page end-->		 
    </section>
</section>