<div class="span4 box">
    <div class="content-wrap">
        <h6>Forgot password</h6>
        <?php if ($this->successmessage != ''): ?>
            <div class="alert alert-success">
                <i class="icon-ok-sign"></i> <?php echo $this->successmessage; ?>
            </div>
        <?php endif; ?>
        <?php if (count($this->errorMessage) > 0): ?>
            <div class="alert alert-error">
                <?php foreach ($this->errorMessage as $erroValue): ?>
                    <?php foreach ($erroValue as $_value): ?>
                        <div class="text-left">
                            <i class="icon-remove-sign"></i>
                            <?php echo $_value; ?>
                        </div>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <form id="forgotpasswordfrm" action="" method="post">	
            <?php echo $this->form->email; ?>
            <a href="<?php echo $this->url(array('module' => 'admin','controller' => 'login', 'action' => 'index'), null, TRUE); ?>" class="forgot">Log in</a>
            <button type="submit" class="btn-glow primary login">
                Submit
            </button>
        </form>	
    </div>
</div>