<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Gigable">
        <meta name="keyword" content="Gigable Admin Portal">
        <link rel="shortcut icon" href="<?php echo $this->ADMIN_PATH; ?>img/favicon.png">

        <title><?php echo $this->SITE_NAME; ?></title>

        <!-- Bootstrap core CSS -->
        <link href="<?php echo $this->ADMIN_PATH; ?>css/bootstrap.min.css" rel="stylesheet">
        <link href="<?php echo $this->ADMIN_PATH; ?>css/bootstrap-reset.css" rel="stylesheet">
        <!--external css-->
        <link href="<?php echo $this->ADMIN_PATH; ?>assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
        <link href="<?php echo $this->ADMIN_PATH; ?>assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen"/>
        <link rel="stylesheet" href="<?php echo $this->ADMIN_PATH; ?>css/owl.carousel.css" type="text/css">

        <!--right slidebar-->
        <link href="<?php echo $this->ADMIN_PATH; ?>css/slidebars.css" rel="stylesheet">

        <!-- Custom styles for this template -->

        <link href="<?php echo $this->ADMIN_PATH; ?>css/style.css" rel="stylesheet">
        <link href="<?php echo $this->ADMIN_PATH; ?>css/style-responsive.css" rel="stylesheet" />

        <link href="<?php echo $this->ADMIN_PATH; ?>css/developer.css" rel="stylesheet" />
		
		<link href="<?php echo $this->ADMIN_PATH; ?>plugin/bootstrap-select2/select2.css" rel="stylesheet" type="text/css" media="screen"/>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
        <!--[if lt IE 9]>
          <script src="<?php echo $this->ADMIN_PATH; ?>js/html5shiv.js"></script>
          <script src="<?php echo $this->ADMIN_PATH; ?>js/respond.min.js"></script>
        <![endif]-->

        <?php echo $this->headLink(); ?>
        <script>
            var BASE_PATH = '<?php echo BASE_PATH; ?>';
            var SITE_URL = '<?php echo $this->BASE_URL . ""; ?>';
        </script>

    </head>

    <body>

        <section id="container" >
            <!--header start-->
            <header class="header white-bg">
                <div class="sidebar-toggle-box">
                    <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
                </div>
                <!--logo start-->
                <a href="<?php echo $this->BASE_URL; ?>admin" class="logo"><img alt="" src="<?php echo $this->ADMIN_PATH; ?>img/logo.png"class="good_logo"></a>
                <!--logo end-->

                <div class="top-nav ">
                    <!--search & user info start-->
                    <ul class="nav pull-right top-menu">

                        <!-- user login dropdown start-->
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <!--<img alt="" src="<?php echo $this->ADMIN_PATH; ?>img/avatar1_small.jpg">-->
								<i class="fa fa-user"></i>&nbsp;
                                <span class="username"><?php echo $this->user->admin_firstname; ?>&nbsp;<?php echo $this->user->admin_lastname; ?></span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu extended logout">
                                <div class="log-arrow-up"></div>
                                <li><a href="<?php echo $this->BASE_URL; ?>admin/adminuser/editprofile"><i class=" fa fa-suitcase"></i>Profile</a></li>
                                <!--<li><a href="#"><i class="fa fa-cog"></i> Settings</a></li>
                                <li><a href="#"><i class="fa fa-bell-o"></i> Notification</a></li>-->
                                <li><a href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'logout', 'action' => 'index'), null, TRUE); ?>"><i class="fa fa-key"></i> Log Out</a></li>
                            </ul>
                        </li>
                        <!-- user login dropdown end -->
                    </ul>
                    <!--search & user info end-->
                </div>
            </header>
            <!--header end-->
            <!--sidebar start-->
            <aside>
                <div id="sidebar"  class="nav-collapse ">
                    <!-- sidebar menu start-->
                    <ul class="sidebar-menu" id="nav-accordion">
                        <li>
                            <a <?php if ($this->CONTROLLER_NAME == "index" && $this->ACTION_NAME == "index"): ?> class="active" <?php endif; ?> href="<?php echo $this->BASE_URL; ?>admin">
                                <i class="fa fa-dashboard"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>
						<!-- LANGUAGE MENU-----> 
                        <!--<li class="sub-menu">
                            <a <?php if ($this->CONTROLLER_NAME == "language" && $this->ACTION_NAME == "list"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "language", "action" => "list"), null, TRUE); ?>">
                                <i class="fa fa-globe"></i>
                                <span>Language</span>
                            </a>
                        </li>-->						
						<!-- CATEGORY MENU-----> 
                        <li class="sub-menu">
                            <a <?php if ($this->CONTROLLER_NAME == "category" && $this->ACTION_NAME == "list"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "category", "action" => "list"), null, TRUE); ?>">
                                <i class="fa fa-tags"></i>
                                <span>Category</span>
                            </a>
                        </li>
						
						<li class="sub-menu">
                            <a <?php if ($this->CONTROLLER_NAME == "cms" && $this->ACTION_NAME == "list"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "cms", "action" => "list"), null, TRUE); ?>">
                                <i class="fa fa-tags"></i>
                                <span>CMS</span>
                            </a>
                        </li>
						<!-- Location MENU-----> 
                       <!-- <li class="sub-menu">
                            <a <?php if ($this->CONTROLLER_NAME == "location" && $this->ACTION_NAME == "list"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "location", "action" => "list"), null, TRUE); ?>">
                                <i class="fa fa-map-marker"></i>
                                <span>Location</span>
                            </a>
                        </li>-->
						
						<!-- Post MENU-----> 
                        <li class="">
                            <a <?php if ($this->CONTROLLER_NAME == "post" && $this->ACTION_NAME == "list"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "list"), null, TRUE); ?>">
                                <i class="fa fa-book"></i>
                                <span>Post</span>
                            </a>
							<ul class="submenu" style="display: none;">
								<li>
									<a <?php if ($this->CONTROLLER_NAME == "post" && $this->ACTION_NAME == "list"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "list"), null, TRUE); ?>">
										<i class="fa fa-book"></i>
										<span>All Post</span>
									</a>
								</li>
								<li>
									<a <?php if ($this->CONTROLLER_NAME == "post" && $this->ACTION_NAME == "approvepostlist"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "approvepostlist"), null, TRUE); ?>">
										<i class="fa fa-book"></i>
										<span>Approved Post</span>
									</a>
								</li>
								<li>
									<a <?php if ($this->CONTROLLER_NAME == "post" && $this->ACTION_NAME == "rejectpostlist"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "rejectpostlist"), null, TRUE); ?>">
										<i class="fa fa-book"></i>
										<span>Rejected Post</span>
									</a>
								</li>
								<li>
									<a <?php if ($this->CONTROLLER_NAME == "post" && $this->ACTION_NAME == "pendingpostlist"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "pendingpostlist"), null, TRUE); ?>">
										<i class="fa fa-book"></i>
										<span>Pending Post</span>
									</a>
								</li>
								
								<li>
									<a <?php if ($this->CONTROLLER_NAME == "post" && $this->ACTION_NAME == "likepostlist"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "likepostlist"), null, TRUE); ?>">
										<i class="fa fa-book"></i>
										<span>Most Liked Post</span>
									</a>
								</li>
								
								<li>
									<a <?php if ($this->CONTROLLER_NAME == "post" && $this->ACTION_NAME == "dislikepostlist"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "dislikepostlist"), null, TRUE); ?>">
										<i class="fa fa-book"></i>
										<span>Most Unliked Post</span>
									</a>
								</li>
								
								<li>
									<a <?php if ($this->CONTROLLER_NAME == "post" && $this->ACTION_NAME == "commentpostlist"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "post", "action" => "commentpostlist"), null, TRUE); ?>">
										<i class="fa fa-book"></i>
										<span>Most Commented Post</span>
									</a>
								</li>
							</ul>
						</li>	
                      		
						<!-- User MENU-----> 
                        <li class="sub-menu">
                            <a <?php if ($this->CONTROLLER_NAME == "user" && $this->ACTION_NAME == "list"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "user", "action" => "list"), null, TRUE); ?>">
                                <i class="fa fa-user"></i>
                                <span>User</span>
                            </a>
                        </li>
						
						<!-- Admin MENU-----> 
                        <li class="sub-menu">
                            <a <?php if ($this->CONTROLLER_NAME == "adminuser" && $this->ACTION_NAME == "list"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "adminuser", "action" => "list"), null, TRUE); ?>">
                                <i class="fa fa-user"></i>
                                <span>Admin Management</span>
                            </a>
                        </li>														
						<!-- SETTING MENU-----> 
                        <li class="sub-menu">
                            <a <?php if ($this->CONTROLLER_NAME == "metadata" && $this->ACTION_NAME == "form"): ?> class="active" <?php endif; ?> href="<?php echo $this->url(array("module" => "admin", "controller" => "metadata", "action" => "form"), null, TRUE); ?>">
                                <i class="fa fa-gears"></i>
                                <span>Setting</span>
                            </a>
                        </li>
						
						<!-- LOGOUT MENU-----> 
						<li>
                            <a  href="<?php echo $this->url(array('module' => 'admin', 'controller' => 'logout', 'action' => 'index'), null, TRUE); ?>">
                                <i class="fa fa-key"></i>
                                <span>Logout</span>
                            </a>
                        </li>
                    </ul>
                    <!-- sidebar menu end-->
                </div>
            </aside>
            <!--sidebar end-->
            <?php echo $this->layout()->content; ?>
			<?php echo $this->partial('partial/modal.phtml'); ?>
            <!--footer start-->
            <footer class="site-footer">
                <div class="text-center">
                    2016 &copy; Aqceptence LLC.
                    <a href="#" class="go-top">
                        <i class="fa fa-angle-up"></i>
                    </a>
                </div>
            </footer>
            <!--footer end-->
        </section>     

        <!-- js placed at the end of the document so the pages load faster -->
        <script src="<?php echo $this->ADMIN_PATH; ?>js/jquery.js"></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>js/project.js"></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>js/bootstrap.min.js"></script>

        <?php if($this->ACTION_NAME == 'trackorder'):?>
            <link rel="stylesheet" type="text/css" href="<?php echo $this->ADMIN_PATH; ?>assets/nestable/jquery.nestable.css" />
            <script src="<?php echo $this->ADMIN_PATH; ?>assets/nestable/jquery.nestable.js"></script>
            <script src="<?php echo $this->ADMIN_PATH; ?>js/nestable.js"></script>
        <?php endif;?>
 
    
        <script class="include" type="text/javascript" src="<?php echo $this->ADMIN_PATH; ?>js/jquery.dcjqaccordion.2.7.js"></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>js/jquery.scrollTo.min.js"></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>js/jquery.nicescroll.js" type="text/javascript"></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>assets/jquery-knob/js/jquery.knob.js"></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>js/jquery.sparkline.js" type="text/javascript"></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>js/owl.carousel.js" ></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>js/jquery.customSelect.min.js" ></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>js/respond.min.js" ></script>
<script src="<?php echo $this->ADMIN_PATH; ?>dropzone/dropzone.js" type="text/javascript"></script>
        <!--right slidebar-->
        <script src="<?php echo $this->ADMIN_PATH; ?>js/slidebars.min.js"></script>

        <!--common script for all pages-->
        <script src="<?php echo $this->ADMIN_PATH; ?>js/common-scripts.js"></script>

        <!--script for this page-->
        <script src="<?php echo $this->ADMIN_PATH; ?>js/sparkline-chart.js"></script>
        <script src="<?php echo $this->ADMIN_PATH; ?>js/easy-pie-chart.js"></script>
		<script src="<?php echo $this->ADMIN_PATH; ?>plugin/bootstrap-select2/select2.min.js" type="text/javascript"></script>
        <!--<script src="<?php echo $this->ADMIN_PATH; ?>js/count.js"></script>-->
     <?php echo $this->headScript(); ?>
		<script src="<?php echo $this->ADMIN_PATH; ?>js/general.js"></script>
        <script>
            //knob
			$(".knob").knob();
        </script>
		
		<script type="text/javascript">
			/*$(document).ready(function() {
				$(function(){
					$('select').customSelect();
				});
			});*/
		</script>

        <script>
            //owl carousel
            $(document).ready(function() {
                $("#owl-demo").owlCarousel({
                    navigation: true,
                    slideSpeed: 300,
                    paginationSpeed: 400,
                    singleItem: true,
                    autoPlay: true
                });
            });

            //custom select box
            $(function() {
                $('select.styled').customSelect();
            });
        </script>
    </body>
</html>
