<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie10 lt-ie9 lt-ie8 lt-ie7" lang="en-us"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie10 lt-ie9 lt-ie8" lang="en-us"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie10 lt-ie9" lang="en-us"> <![endif]-->
<!--[if IE 9]> <html class="no-js lt-ie10 lt-ie9" lang="en-us"> <![endif]-->
<!--[if lt IE 10]> <html class="no-js lt-ie10" lang="en-us"> <![endif]-->
<!--[if !IE]> > <![endif]-->
<html class='no-js' lang='en'>
<!-- <![endif] -->
<head>
<meta name="description" content="" />
<meta name="author" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<title><?php echo $this->SITE_NAME; ?></title>

<meta content='initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width' name='viewport' />
<meta content='yes' name='apple-mobile-web-app-capable'>
<meta content='translucent-black' name='apple-mobile-web-app-status-bar-style'>
<link href='<?php echo $this->FRONT_IMAGE_PATH; ?>favicon.png' rel='shortcut icon'>
<link href='<?php echo $this->FRONT_IMAGE_PATH; ?>favicon.ico' rel='icon' type='image/ico'>

<link href="https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700" rel="stylesheet"> 

<link href="<?php echo $this->FRONT_CSS_PATH; ?>style.css" media="all" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->FRONT_CSS_PATH; ?>bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->FRONT_CSS_PATH; ?>font-awesome.min.css" media="all" rel="stylesheet" type="text/css" />

<link href="<?php echo $this->FRONT_CSS_PATH; ?>animate.css" rel="stylesheet" />
<link href="<?php echo $this->FRONT_CSS_PATH; ?>developer.css" rel="stylesheet" />
<link href="http://vjs.zencdn.net/4.0/video-js.css" rel="stylesheet">
 <script src="http://vjs.zencdn.net/4.0/video.js"></script>
<script src="<?php echo $this->FRONT_JS_PATH; ?>modernizr.js" type="text/javascript"></script>
    <!--[if IE]>
	<script src="js/html5.js"></script>
	<![endif]-->

</head>
<body>

<div id="wrapper">

	<header>
    	<div class="header-div inner-header-div clearfix">
        	<div class="logo-div">
            	<a href="<?php echo $this->BASE_URL; ?>"><img src="<?php echo $this->FRONT_IMAGE_PATH; ?>logo.png" alt=""></a>
            </div>
           <!-- <div class="location-top-div">
            	<div class="location-div"><i class="fa fa-crosshairs"></i> Get Location</div>
            </div>-->
            
            <div class="nav-div">
            	
                  <nav class="navbar">
                    <div class="navbar-header">
                      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </button>
                    </div>
                
                
                    <div class="collapse navbar-collapse js-navbar-collapse">
                      <ul class="nav navbar-nav">
                        <li class="dropdown mega-dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Explore <span class="fa fa-angle-down "></span></a>
                
                          <ul class="dropdown-menu mega-dropdown-menu row">
                          	 	<li class="col-md-12 col-sm-12"><a href="exlpore.html">All Listings</a></li>
                                <li class="col-md-4 col-sm-4"><a href="food.html">food</a></li>
                                <li class="col-md-4 col-sm-4"><a href="road.html">Road</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 3</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 4</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 5</a></li>
                                 <li class="col-md-4 col-sm-4"><a href="food.html">food</a></li>
                                <li class="col-md-4 col-sm-4"><a href="road.html">Road</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 3</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 4</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 5</a></li> <li class="col-md-4 col-sm-4"><a href="food.html">food</a></li>
                                <li class="col-md-4 col-sm-4"><a href="road.html">Road</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 3</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 4</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 5</a></li> <li class="col-md-4 col-sm-4"><a href="food.html">food</a></li>
                                <li class="col-md-4 col-sm-4"><a href="road.html">Road</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 3</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 4</a></li>
                                <li class="col-md-4 col-sm-4"><a href="#">Listing 5</a></li>
                          </ul>
                       </li>
                       <li><a href="index.html#howitworks">How It Works</a></li> 
                       <li><a href="#download">Download</a></li> 
                      
                      </ul><!-- end of nav -->
                   </div><!-- end of collapse -->
                </nav>
            
            
            
            
                
            </div><!-- end of nav-div -->
            
            
        </div><!-- end fo header div -->
    
    </header>
	<?php echo $this->layout()->content ?>
	<footer>
    	<div class="footer-social">        
            	<a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-google-plus"></i></a><a href="#"><i class="fa fa-youtube"></i></a><a href="#"><i class="fa fa-linkedin"></i></a>
        </div><!-- end of footer top -->
        <div class="footer-bottom">
        	<div class="container">
            	<p>Copyright &copy; 2016 Good India Bad India.</p>
                <p>Proudly powered by <a href="#">BraineSource</a> and <a href="#">CBCreativeStudio</a>.</p>
            </div>
        </div><!-- end of footer bottom -->
    </footer>
     
     
     
     
    
<div id="back-to-top"><span><i class="fa fa-arrow-up"></i></span></div> 
</div><!-- end of wrapper -->




<script src="<?php echo $this->FRONT_JS_PATH; ?>jquery.min.js" type="text/javascript"></script> 
<script src="<?php echo $this->FRONT_JS_PATH; ?>bootstrap.min.js" type="text/javascript"></script>
<link href="<?php echo $this->FRONT_CSS_PATH; ?>hover-dropdown-menu.css" rel="stylesheet" />
<script type="text/javascript" src="<?php echo $this->FRONT_JS_PATH; ?>hover-dropdown-menu.js"></script>
<!-- Menu jQuery Bootstrap Addon -->
<script type="text/javascript" src="<?php echo $this->FRONT_JS_PATH; ?>jquery.hover-dropdown-menu-addon.js"></script> 

<script type="text/javascript" src="<?php echo $this->FRONT_JS_PATH; ?>home-roundbox-hover.js"></script> 

<script type="text/javascript" src="<?php echo $this->FRONT_JS_PATH; ?>custom.js"></script>

</body>
</html>

    