<?php $this->headScript()->appendFile($this->ADMIN_PATH . "js/setting.js"); ?>
<div id="setting-listing"></div>
<div id="editprofile-listing"></div>
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <!-- page start-->
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
						<?php if ($this->succesMessage != ''): ?>
							<div class="col-lg-12">   
								<div class="alert alert-success">
									<i class="icon-ok-sign"></i>
									<?php echo $this->succesMessage; ?>
								</div>
							</div>
						<?php endif; ?>
						<?php if (count($this->errorMessageArray) > 0): ?>
							<div class="col-lg-12">                  
								<div class="alert alert-block alert-danger fade in">
									<button type="button" class="close close-sm" data-dismiss="alert">
										<i class="fa fa-times"></i>
									</button>
									<?php foreach ($this->errorMessageArray as $erroValue): ?>
										<?php echo $erroValue; ?><br/>
									<?php endforeach; ?>
								</div>
							</div>
						<?php endif; ?>
						
						<header class="panel-heading">Settings</header>
						<div class="panel-body">
							<form role="form"  id="editprofile-form" name="editprofile-form"  enctype="multipart/form-data"  action="" method="post">
								<div class="form-horizontal tasi-form" >
									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label"><span class="error-star">*</span>Admin From Email</label>
										<div class="col-sm-6">
											<?php echo $this->form->ADMIN_FROM_EMAIL; ?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label"><span class="error-star">*</span>Admin From Name</label>
										<div class="col-sm-6">
											<?php echo $this->form->ADMIN_FROM_NAME; ?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label"><span class="error-star">*</span>Paging Per Page</label>
										<div class="col-sm-6">
											<?php echo $this->form->PAGE_RECORD; ?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label"><span class="error-star">*</span>Admin Sign</label>
										<div class="col-sm-6">
											<?php echo $this->form->ADMIN_SIGN; ?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label">Admin Reply</label>
										<div class="col-sm-6">
											<?php echo $this->form->ADMIN_REPLY; ?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label">Admin Reply Name</label>
										<div class="col-sm-6">
											<?php echo $this->form->ADMIN_REPLY_NAME; ?>
										</div>
									</div>									
									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label"></label>
										<div class="col-lg-12 center_button">
											<button class="btn btn-success" type="submit">Update</button>
											<input type="button" class="btn btn-danger cancelbutton" value="Cancel" />
										</div>
									</div>
								</div>
							</form>
						</div>
					</section>
				</div>
				<!-- page end-->
			</div>
		</section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->
<!-- Right Slidebar start -->
<div class="sb-slidebar sb-right sb-style-overlay">
    <h5 class="side-title">Online Customers</h5>
    <ul class="quick-chat-list">
        <li class="online">
            <div class="media">
                <a href="#" class="pull-left media-thumb">
                    <img alt="" src="img/chat-avatar2.jpg" class="media-object">
                </a>
                <div class="media-body">
                    <strong>John Doe</strong>
                    <small>Dream Land, AU</small>
                </div>
            </div><!-- media -->
        </li>
        <li class="online">
            <div class="media">
                <a href="#" class="pull-left media-thumb">
                    <img alt="" src="img/chat-avatar.jpg" class="media-object">
                </a>
                <div class="media-body">
                    <div class="media-status">
                        <span class=" badge bg-important">3</span>
                    </div>
                    <strong>Jonathan Smith</strong>
                    <small>United States</small>
                </div>
            </div><!-- media -->
        </li>

        <li class="online">
            <div class="media">
                <a href="#" class="pull-left media-thumb">
                    <img alt="" src="img/pro-ac-1.png" class="media-object">
                </a>
                <div class="media-body">
                    <div class="media-status">
                        <span class=" badge bg-success">5</span>
                    </div>
                    <strong>Jane Doe</strong>
                    <small>ABC, USA</small>
                </div>
            </div><!-- media -->
        </li>
        <li class="online">
            <div class="media">
                <a href="#" class="pull-left media-thumb">
                    <img alt="" src="img/avatar1.jpg" class="media-object">
                </a>
                <div class="media-body">
                    <strong>Anjelina Joli</strong>
                    <small>Fockland, UK</small>
                </div>
            </div><!-- media -->
        </li>
        <li class="online">
            <div class="media">
                <a href="#" class="pull-left media-thumb">
                    <img alt="" src="img/mail-avatar.jpg" class="media-object">
                </a>
                <div class="media-body">
                    <div class="media-status">
                        <span class=" badge bg-warning">7</span>
                    </div>
                    <strong>Mr Tasi</strong>
                    <small>Dream Land, USA</small>
                </div>
            </div><!-- media -->
        </li>
    </ul>
    <h5 class="side-title"> pending Task</h5>
    <ul class="p-task tasks-bar">
        <li>
            <a href="#">
                <div class="task-info">
                    <div class="desc">Dashboard v1.3</div>
                    <div class="percent">40%</div>
                </div>
                <div class="progress progress-striped">
                    <div style="width: 40%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="40" role="progressbar" class="progress-bar progress-bar-success">
                        <span class="sr-only">40% Complete (success)</span>
                    </div>
                </div>
            </a>
        </li>
        <li>
            <a href="#">
                <div class="task-info">
                    <div class="desc">Database Update</div>
                    <div class="percent">60%</div>
                </div>
                <div class="progress progress-striped">
                    <div style="width: 60%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="60" role="progressbar" class="progress-bar progress-bar-warning">
                        <span class="sr-only">60% Complete (warning)</span>
                    </div>
                </div>
            </a>
        </li>
        <li>
            <a href="#">
                <div class="task-info">
                    <div class="desc">Iphone Development</div>
                    <div class="percent">87%</div>
                </div>
                <div class="progress progress-striped">
                    <div style="width: 87%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" class="progress-bar progress-bar-info">
                        <span class="sr-only">87% Complete</span>
                    </div>
                </div>
            </a>
        </li>
        <li>
            <a href="#">
                <div class="task-info">
                    <div class="desc">Mobile App</div>
                    <div class="percent">33%</div>
                </div>
                <div class="progress progress-striped">
                    <div style="width: 33%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="80" role="progressbar" class="progress-bar progress-bar-danger">
                        <span class="sr-only">33% Complete (danger)</span>
                    </div>
                </div>
            </a>
        </li>
        <li>
            <a href="#">
                <div class="task-info">
                    <div class="desc">Dashboard v1.3</div>
                    <div class="percent">45%</div>
                </div>
                <div class="progress progress-striped active">
                    <div style="width: 45%" aria-valuemax="100" aria-valuemin="0" aria-valuenow="45" role="progressbar" class="progress-bar">
                        <span class="sr-only">45% Complete</span>
                    </div>
                </div>

            </a>
        </li>
        <li class="external">
            <a href="#">See All Tasks</a>
        </li>
    </ul>
</div>
<!-- Right Slidebar end -->