<table width="100%" cellspacing="0" cellpadding="0" border="0">
    <tbody><tr><td height="30"></td></tr>
        <tr bgcolor="#F1F2F7">
            <td width="100%" valign="top" bgcolor="#F1F2F7" align="center">
                <!--  top header -->
                <table class="container" width="600" cellspacing="0" cellpadding="0" border="0" align="center">
                    <tbody>
                        <tr bgcolor="7087A3"><td height="15"></td></tr>
                        <tr bgcolor="7087A3">
                            <td align="center">
                                <table class="container-middle" width="560" cellspacing="0" cellpadding="0" border="0" align="center">
                                    <tbody><tr>
                                            <td>
                                                <table class="top-header-left" cellspacing="0" cellpadding="0" border="0" align="left">
                                                    <tbody>
														<tr>
                                                            <td align="center">
                                                                <table class="date" cellspacing="0" cellpadding="0" border="0">
																	<tbody>
																		<tr>
                                                                            <td>
                                                                                <img style="display: block;" src="<?php echo $this->public_admin_path; ?>img/logo.png" alt="icon 1" width="25" height="25"></td>&nbsp;&nbsp;<td style="color: #fefefe; font-size: 11px; font-weight: normal; font-family: Helvetica, Arial, sans-serif;"><singleline><?php echo date('l d F, Y'); ?></singleline> </td>
																			</tr>
																		</tbody>
																	</table>
																</td>
															</tr>
														</tbody>
													</table>
												</td>
												<table class="top-header-right" cellspacing="0" cellpadding="0" border="0" align="left">
												<tbody><tr><td width="30" height="20"></td></tr></tbody></table>

												<table class="top-header-right" cellspacing="0" cellpadding="0" border="0" align="right">
													<tbody><tr>
														<td align="center">
															<table class="tel" cellspacing="0" cellpadding="0" border="0" align="center">
																<tbody>
																	<tr>
																		<td></td><td>&nbsp;&nbsp;</td>
																			<td style="color: #fefefe; font-size: 11px; font-weight: normal; font-family: Helvetica, Arial, sans-serif;"><singleline></singleline></td></tr></tbody></table></td></tr> </tbody></table>
								</td>
							</tr></tbody>
						</table>
				</td>
			</tr>
			<tr bgcolor="7087A3"><td height="10"></td></tr>
		</tbody>
	</table>
<!--  end top header  -->

<!-- main content -->
<table class="container" width="600" cellspacing="0" cellpadding="0" border="0" bgcolor="ffffff" align="center">
   <!--Header-->
    <tbody><tr><td height="40"></td></tr>
		<tr>
			<td>
				<table class="container-middle" width="560" cellspacing="0" cellpadding="0" border="0" align="center">
                    <tbody>
						<tr>
                            <td>
                                <table class="logo" cellspacing="0" cellpadding="0" border="0" align="center">
                                    <tbody>
										<tr>
                                            <td class="main-header" style="align:center;color: #484848; font-size: 16px; font-weight: normal; font-family: Helvetica, Arial, sans-serif;">Verified successfully</td>
                                        </tr>
                                    </tbody>
								</table>
							</td>
                        </tr>
                    </tbody>
				</table>
            </td>
        </tr>
        <tr><td height="40"></td></tr>
        <!-- end header -->
        <!-- main section -->
        <tr>
            <td>
                <table class="container-middle" width="560" cellspacing="0" cellpadding="0" border="0" align="center">
                    <tbody>
                        <tr>
                            <td>
                                <table class="mainContent" width="528" cellspacing="0" cellpadding="0" border="0" align="center">
                                    <tbody>
                                        <tr>
                                            <td class="main-subheader" style="color: #a4a4a4; font-size: 12px; font-weight: normal; line-height:20px; font-family: Helvetica, Arial, sans-serif;">
                                                Email: <?php echo $this->email; ?><br/>
                                               
											   
                                            </td>
                                        </tr>
                                    </tbody>
								</table>
                            </td>
                        </tr>
                        <tr><td height="25"></td></tr>
                    </tbody>
				</table>
            </td>
        </tr>
        <!-- end main section -->
		<tr><td height="35"></td></tr>
	</tbody>
</table>
<!--end main Content -->

<!-- footer -->
<table class="container" width="600" cellspacing="0" cellpadding="0" border="0">
    <tbody>
        <tr bgcolor="7087A3"><td height="15"></td></tr>
        <tr bgcolor="7087A3">
            <td style="color: #fff; font-size: 10px; font-weight: normal; font-family: Helvetica, Arial, sans-serif;" align="center">
                <?php echo $this->ADMIN_COPYRIGHT; ?>
            </td>
        </tr>
        <tr>
            <td bgcolor="7087A3" height="14"></td>
        </tr>
    </tbody>
</table>
<!-- end footer-->
</td>
</tr>
<tr><td height="30"></td></tr>
</tbody>
</table>