<?php $this->headScript()->appendFile($this->ADMIN_PATH . "js/location.js"); ?>
<script>
    var LATITUDE = '<?php echo $this->LATITUDE; ?>';
    var LONGITUDE = '<?php echo $this->LONGITUDE; ?>';
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC3HB97tuqb_MGDjkldqCWI_HqgaQahepk"></script>

<div id="location-listing"></div>
<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <!-- page start-->
            <div class="row">
                <div class="col-lg-12">
                    <section class="panel">
						<?php if ($this->successmessage != ""): ?>
							<div class="alert alert-success">
								<i class="icon-ok-sign"></i> 
								<?php echo $this->successmessage; ?>
							</div>
						<?php endif; ?>
						<?php if (count($this->errorMessageArray) > 0): ?>
							<div class="col-lg-12">                  
								<div class="alert alert-block alert-danger fade in">
									<button type="button" class="close close-sm" data-dismiss="alert">
										<i class="fa fa-times"></i>
									</button>
									<?php foreach ($this->errorMessageArray as $erroValue): ?>
										<?php echo $erroValue; ?><br/>
									<?php endforeach; ?>
								</div>
							</div>
						<?php endif; ?>
						<header class="panel-heading"><?php echo $this->mode; ?> Location
							<a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url(array("module" => "admin", "controller" => "location", "action" => "list"), null, TRUE); ?>">&nbsp;All Location</a>
						</header>
							<div class="panel-body">
								<form role="form"  id="location-form" name="location-form"  enctype="multipart/form-data"  action="" method="post">
								<div class="form-horizontal tasi-form" >
									<div class="form-group">
										
										<div class="col-sm-4">
                                            <label><span class="error-star">*</span>Location</label>
											<?php echo $this->form->loc_name; ?>
                                        </div>
										
                                        <div class="col-sm-6">
                                            <label>&nbsp;</label><br/>
                                            <input type="button" id="search-map" class="btn" value="Search" />
                                            <input type="button" id="current-location" class="btn btn-success" value="Current Location" />
                                        </div>
										
										<div style="clear:both"></div>
										<br>
										<br>
                                    <div class="form-group col-sm-12">
                                        <div class="col-sm-6">
                                            <div id="map-canvas" class="gmaps"></div>
                                        </div>
                                    </div>
                                    <div class="form-group col-sm-12">
                                        <div class="col-sm-3">
											<?php echo $this->form->loc_latitude; ?>
                                        </div>
                                        <div class="col-sm-3">
                                            <?php echo $this->form->loc_longitude; ?>
                                        </div>
                                    </div>
										<div class="col-sm-4">
											<label><span class="error-star">*</span>Status</label>
											<?php echo $this->form->loc_status; ?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-sm-2 col-sm-2 control-label"></label>
										<div class="col-lg-12 center_button">
											<button class="btn btn-success" type="submit" id="location_submit">
												<?php if($this->mode == 'Add'): ?>Save
												<?php else: ?>Update<?php endif; ?>
											</button>
											<input type="button" class="btn btn-danger cancelbutton" value="Cancel" />
										</div>
									</div>
								</div>
							</section>
						</form>
					</div>
				</div>
				<!-- page end-->
			</div>
		</section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->