<?php $this->headScript()->appendFile($this->ADMIN_PATH . "js/location.js"); ?>
<div id="location-listing"></div>
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-lg-12">
                <?php echo $this->flashmessages(); ?>
                <?php if (count($this->errorMessage) > 0): ?>
                    <div class="col-lg-12">                  
                        <div class="alert alert-block alert-danger fade in">
                            <button type="button" class="close close-sm" data-dismiss="alert">
                                <i class="fa fa-times"></i>
                            </button>
                            <?php foreach ($this->errorMessage as $erroValue): ?>
                                <?php echo $erroValue; ?><br/>
                            <?php endforeach; ?>
                        </div>
                    </div>
                <?php endif; ?>
                <form action="" method="post" id="propertylocationlistingform">
                    <section class="panel">
                        <header class="panel-heading">
                            Location List

                            <?php if (count($this->locationsData) > 0): ?> 
                                <div class="delete_All pull-right">    
                                    &nbsp;&nbsp;<input type="submit" accesskey="s" value="Delete All" name="multiaction"  id="multiaction" class="btn btn-sm btn-danger delete_all"/>      
                                </div>
                            <?php else: ?>
                                &nbsp;
                            <?php endif; ?>

							<!--<a id="add_location" class="btn btn-success btn-sm pull-right" href="#" data-toggle="modal" mode="Add Property Location">&nbsp;+ Add</a>-->
							
							<a href="<?php echo $this->url(array('controller' => 'location', 'action' => 'form', 'module' => 'admin'), 'default', false); ?>" data-toggle="modal" title="Add" class="btn btn-success btn-sm pull-right" mode="Add Location">&nbsp;+ Add</a>

                            <div class="form-group col-sm-12 padding_left_0 padding_top_20">

                                <div class="col-sm-2 padding_left_0 padding_right_0">
                                    <input type="text" class="form-control" name="searchtype" value="<?php echo $this->searchtype ?>" >
                                </div>
                                <div class="col-sm-2">
                                    <input class="btn btn-success" id="button-submit" type="submit" value="Search" />
                                    <a class="btn btn-success" href="<?php echo $this->url(array("module" => "admin", 'controller' => 'location', 'action' => 'unsetsession', 'pagename' => 'list'), null, TRUE); ?>">Clear</a>
                                </div>
                            </div>

                        </header>

                        <table class="table table-striped table-advance table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        <input id="selectall" type="checkbox"/>
                                        <a href="<?php echo $this->url(array('controller' => 'location', 'action' => 'list', 'field' => 'loc_name', 'sort' => 'asc', 'module' => 'admin'), 'default', false); ?>">
                                            <img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_asc.png"  alt="Ascending" title="Ascending" class="sort_asc" />
                                        </a>
                                        <i class="fa fa-map-marker"></i> Name
                                        <a href="<?php echo $this->url(array('controller' => 'location', 'action' => 'list', 'field' => 'loc_name', 'sort' => 'desc', 'module' => 'admin'), 'default', false); ?>">
                                            <img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_desc.png"  alt="Descending" title="Descending" class="sort_desc"  />
                                        </a>
                                    </th>                               
                                    <th>
                                        <a href="<?php echo $this->url(array('controller' => 'location', 'action' => 'list', 'field' => 'loc_status', 'sort' => 'asc', 'module' => 'admin'), 'default', false); ?>">
                                            <img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_asc.png"  alt="Ascending" title="Ascending" class="sort_asc" />
                                        </a>
                                        <i class="fa fa-check-square-o"></i> Status
                                        <a href="<?php echo $this->url(array('controller' => 'location', 'action' => 'list', 'field' => 'loc_status', 'sort' => 'desc', 'module' => 'admin'), 'default', false); ?>">
                                            <img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_desc.png"  alt="Descending" title="Descending" class="sort_desc"  />
                                        </a>
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if (count($this->locationsData) > 0): ?>
                                    <?php foreach ($this->locationsData as $key => $value) : ?>
                                        <tr>
                                           <td>
                                                <input type="checkbox" class="content-checkbox chek_all" name="multicheck[]" value="<?php echo $value["loc_id"]; ?>"/>&nbsp;
												<a href="<?php echo $this->url(array("module" => "admin", "controller" => "location", "action" => "form", "loc_id" => $value["loc_id"]), null, true); ?>" title="Edit" >
													<?php echo $value["loc_name"]; ?>
												</a>
                                            </td>
											
                                            <td>
												<?php 
													if($value['loc_status'] == 1){	
														$loc_status = 'InActive';
													} else {
														$loc_status = 'Active';
													}
												?>
                                                <a href="#" class="myLink" loc_status="<?php echo $loc_status; ?>" href_link="<?php echo $this->url(array("module" => "admin", "controller" => "location", "action" => "changestatus", "loc_status" => $value["loc_status"], "loc_id" => $value["loc_id"]), null, true); ?>">
                                                    <?php if ($value["loc_status"] == 1): ?>
                                                        <span class="label label-success label-mini">Active</span>
                                                    <?php else: ?>
                                                        <span class="label label-warning label-mini">InActive</span>
                                                    <?php endif; ?>
                                                </a>
                                            </td>
                                            <td>
                                                <a href="<?php echo $this->url(array("module" => "admin", "controller" => "location", "action" => "form", "loc_id" => $value["loc_id"]), null, true); ?>" title="Edit" class="btn btn-primary btn-xs">
                                                    <i class="fa fa-pencil"></i>
                                                </a>
                                                <a href="#" title="Delete" class="btn btn-danger btn-xs deletemodal" target_href="<?php echo $this->url(array("module" => "admin", "controller" => "location", "action" => "delete", "loc_id" => $value["loc_id"]), null, true); ?>">
                                                    <i class="fa fa-trash-o"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr class="row2" >
                                        <td>&nbsp;</td>
                                        <td colspan="8"> No Record Found</td>
                                    </tr>
                                <?php endif; ?>
                            </tbody>
                        </table>

                        <div class="panel-body">
                            <div>
                                <?php
                                if (count($this->locationsData) > 0):
                                    echo $this->paginator->displayPages();
                                endif;
                                ?>
                            </div>
                        </div>				  
                    </section>	
                </form>
            </div>
        </div>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

<!-- Modal -->
<div class="modal fade" id="update_status_Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
                <br/>
                <i class="icon-credit-card icon-7x"></i>
                <input type="hidden" id="hidden_image_type" value=""/>
                <input type="hidden" id="hidden_image_id" value=""/>
                <h4 id="myModalLabel" class="semi-bold add_status"></h4>
                <br/>
            </div>
            <div class="modal-footer">
                <a href="#" class="update_status_link btn btn-danger">submit</a>
                <a href="#" data-dismiss="modal" class="btn btn-default">Cancel</a>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

