<?php
$propertylocation_model = $this->propertylocationalldata;
?>

		<div id="pad-wrapper">
    <div class="row pagelist-header">
        <h3>Propertylocation Detail</h3>
    </div>
    <div class="table-products">
        <div class="row-fluid ">
            <div class="pull-right">
                <a class="btn-flat new-product" href="<?php echo $this->url(array("module" => "admin", "controller" => "propertylocation", "action" => "list"), null, TRUE); ?>"> Back</a>
            </div>              
        </div><div class="main_detail">
                        <div class="sub_main">
                            <div class="detail_label">Name: </div>
                            <div class="detail_data">
                            <?php echo ucfirst($propertylocation_model["ploc_name"]); ?></div>
                        </div>
		
                        <div class="sub_main">
                            <div class="detail_label">: </div>
                            <div class="detail_data">
                            <?php echo ucfirst($propertylocation_model["ploc_createddate"]); ?></div>
                        </div>
		
                        <div class="sub_main">
                            <div class="detail_label">: </div>
                            <div class="detail_data">
                            <?php echo ucfirst($propertylocation_model["ploc_updateddate"]); ?></div>
                        </div>
		
                        <div class="sub_main">
                            <div class="detail_label">Status: </div>
                            <div class="detail_data">
                                <?php echo ( $propertylocation_model["ploc_status"] == 1 ) ? "Active" : "Inactive"; ?>
                            </div>
                        </div>
		 </div>
         </div>
    </div>