<?php $this->headScript()->appendFile($this->JS_PATH . "user.js"); ?>
<div id="user-listing"></div>
<?php $user_model = $this->useralldata; ?>
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <div class="border-head">
                    <h3>User Detail
					<a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url(array("module" => "admin", "controller" => "user", "action" => "list"), null, TRUE); ?>">&nbsp;All Users</a>
					</h3>
                </div>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <div class="panel-body">
                        <div class="col-md-6">
                            <div class="product_meta">
								 <ol class="dd-list">
									<div class="detail_label">User ID: </div>
									<div class="dd-handle">
										<?php echo ucfirst($user_model["usr_id"]); ?>
									</div>
								</ol>
								 <ol class="dd-list">
									<div class="detail_label">Email: </div>
									<div class="dd-handle">
										<?php echo ucfirst($user_model["lgn_email"]); ?>
									</div>
								</ol>
								<ol class="dd-list">
									<div class="detail_label">Name: </div>
									<div class="dd-handle">
										<?php echo ucfirst($user_model["usr_name"]); ?>
									</div>
								</ol>
								<?php if($user_model["usr_phone"] != ""){?>
								<ol class="dd-list">
									<div class="detail_label">Phone: </div>
									<div class="dd-handle">
										<?php echo $user_model["usr_phone"]; ?>
									</div>
								</ol>
								<?php }?>
								<?php if($user_model["usr_image"] != ""){?>
								<ol class="dd-list">
									<div class="detail_label">Image: </div>
									<div class="dd-handle">
									<img src="<?php echo $this->PUBLIC_PATH;?>upload/user/<?php echo ucfirst($user_model["usr_image"]); ?>" height="200" width="200">
									</div>
								</ol>
								<?php }?>
								
								<ol class="dd-list">
									<div class="detail_label">Gender: </div>
									<div class="dd-handle">
									<?php if ($user_model["usr_gender"] == 0){ 								
											$gender = 'Female';}
										else{ 
											$gender = 'Male';
											} ?>
										<?php echo $gender; ?>
									</div>
								</ol>
							</div>
						</div>
						<div class="col-md-6">
                            <div class="product_meta">
							<ol class="dd-list">
								<div class="detail_label">Type: </div>
								<div class="dd-handle">
									<?php if($user_model["usr_lgn_type"]==1){
									echo "Android";}else{
										echo "IOS";
									}?>
								</div>
                            </ol>
							
							<ol class="dd-list">
								<div class="detail_label">Login Type: </div>
								<div class="dd-handle">
									<?php 
										if($user_model["lgn_type"] == 2){
											$type =  "Normal User";
										} else if ($user_model["lgn_type"] == 3){
											$type = "Facebook";
										} else {
											$type = "Google";
										} 
									?><?php echo $type; ?>
								</div>
                            </ol>
							
							
							<ol class="dd-list">
								<div class="detail_label">CreatedDate: </div>
								<div class="dd-handle">
									<?php echo $this->gtlObj->formatdatetime($user_model["usr_createddate"],'d/m/Y'); ?>
								</div>
                            </ol>
							<ol class="dd-list">
								<div class="detail_label">UpdatedDate: </div>
								<div class="dd-handle">
									<?php echo $this->gtlObj->formatdatetime($user_model["usr_updateddate"],'d/m/Y'); ?>
								</div>
                            </ol>
							<ol class="dd-list">
								<div class="detail_label">Status: </div>
								<div class="dd-handle">
									 <?php echo ( $user_model["usr_status"] == 1 ) ? "Active" : "Inactive"; ?>
								</div>
                            </ol>
                        </div>
						</div>
                    </div>
                </section>
            </div>
			<div class="col-lg-12">
                <section class="panel">
                    <header class="panel-heading">Assign Video Detail</header>
                    <table class="table table-striped table-advance table-hover">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Category</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if (count($this->privateuserdata) > 0): ?>
                                <?php foreach ($this->privateuserdata as $key => $value): ?>
                                    <tr>
                                        <td><?php echo $value['vid_title']; ?></td>
										<td><?php echo $value['cat_name']; ?></td>
                                        <td>
                                            <?php if ($value["vid_status"] == 1): ?>
                                                <span class="label label-success label-mini">Active</span>
                                            <?php else: ?>
                                                <span class="label label-warning label-mini">InActive</span>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
						<?php else: ?>
                                <tr class="row2" >
                                    <td>&nbsp;&nbsp;</td>
                                    <td colspan="8"> No Record Found</td>
                                </tr>
						<?php endif; ?>
                        </tbody>
                    </table>
                </section>
            </div>
		</div>
		<a class="btn btn-success btn-sm pull-left" href="<?php echo $this->url(array("module" => "admin", "controller" => "user", "action" => "list"), null, TRUE); ?>">&nbsp;Back</a>
    </section>
</section>
<!--main content end-->
