<?php $this->headScript()->appendFile($this->ADMIN_PATH . "js/admin_user.js"); ?>
<div id="adminuser-listing"></div>
<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<!-- page start-->
		<div class="row">
			<div class="col-lg-12">
				<?php echo $this->flashmessages(); ?>
				<?php if (count($this->errorMessage) > 0): ?>
					<div class="col-lg-12">                  
						<div class="alert alert-block alert-danger fade in">
							<button type="button" class="close close-sm" data-dismiss="alert">
								<i class="fa fa-times"></i>
							</button>
							<?php foreach ($this->errorMessage as $erroValue): ?>
								<?php echo $erroValue; ?><br/>
							<?php endforeach; ?>
						</div>
					</div>
				<?php endif; ?>
				<form action="" method="post" id="adminuserlistingform">
					<section class="panel">
						<header class="panel-heading">
							Admin User List
							<?php if (count($this->adminuserData) > 0): ?> 
								<div class="delete_All pull-right">    
									&nbsp;&nbsp;<input type="submit" accesskey="s" value="Delete All" name="multiaction"  id="multiaction" class="btn btn-sm btn-danger delete_all"/>      
								</div>	&nbsp;&nbsp;&nbsp;
							<?php else: ?>
								&nbsp;
							<?php endif; ?>
							
							<a class="btn btn-success btn-sm pull-right" href="<?php echo $this->url(array("module" => "admin", "controller" => "adminuser", "action" => "form"), null, TRUE); ?>">&nbsp;+ Add</a>
							
						</header>
						
						<table class="table table-striped table-advance table-hover">
							<thead>
								<tr>
									<th>
										<input id="selectall" type="checkbox"/>
										<a href="<?php echo $this->url(array('controller' => 'adminuser', 'action' => 'list', 'field' => 'admin_firstname', 'sort' => 'asc','module' => 'admin'), 'default', false); ?>">
											<img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_asc.png"  alt="Ascending" title="Ascending" class="sort_asc" />
										</a>
										<i class="fa fa-user"></i> Name
										<a href="<?php echo $this->url(array('controller' => 'adminuser', 'action' => 'list', 'field' => 'admin_firstname', 'sort' => 'desc','module' => 'admin'), 'default', false); ?>">
											<img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_desc.png"  alt="Descending" title="Descending" class="sort_desc"  />
										</a>
									</th>
									<th>
										<a href="<?php echo $this->url(array('controller' => 'adminuser', 'action' => 'list', 'field' => 'admin_phone', 'sort' => 'asc','module' => 'admin'), 'default', false); ?>">
											<img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_asc.png"  alt="Ascending" title="Ascending" class="sort_asc" />
										</a>
										<i class="fa fa-phone"></i> Phone no
										<a href="<?php echo $this->url(array('controller' => 'adminuser', 'action' => 'list', 'field' => 'admin_phone', 'sort' => 'desc','module' => 'admin'), 'default', false); ?>">
											<img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_desc.png"  alt="Descending" title="Descending" class="sort_desc"  />
										</a>
									</th>
									<th>
										<a href="<?php echo $this->url(array('controller' => 'adminuser', 'action' => 'list', 'field' => 'admin_email', 'sort' => 'asc','module' => 'admin'), 'default', false); ?>">
											<img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_asc.png"  alt="Ascending" title="Ascending" class="sort_asc" />
										</a>
										<i class="fa fa-envelope-o"></i> Email
										<a href="<?php echo $this->url(array('controller' => 'adminuser', 'action' => 'list', 'field' => 'admin_email', 'sort' => 'desc','module' => 'admin'), 'default', false); ?>">
											<img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_desc.png"  alt="Descending" title="Descending" class="sort_desc"  />
										</a>
									</th>
									<th>	
										<a href="<?php echo $this->url(array('controller' => 'adminuser', 'action' => 'list', 'field' => 'admin_type', 'sort' => 'asc','module' => 'admin'), 'default', false); ?>">
											<img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_asc.png"  alt="Ascending" title="Ascending" class="sort_asc" />
										</a>
										<i class="fa fa-user"></i> Type
										<a href="<?php echo $this->url(array('controller' => 'adminuser', 'action' => 'list', 'field' => 'admin_type', 'sort' => 'desc','module' => 'admin'), 'default', false); ?>">
											<img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_desc.png"  alt="Descending" title="Descending" class="sort_desc"  />
										</a>
									</th>
									<th>
										<a href="<?php echo $this->url(array('controller' => 'adminuser', 'action' => 'list', 'field' => 'admin_status', 'sort' => 'asc','module' => 'admin'), 'default', false); ?>">
											<img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_asc.png"  alt="Ascending" title="Ascending" class="sort_asc" />
										</a>
										<i class="fa fa-check-square-o"></i> Status
										<a href="<?php echo $this->url(array('controller' => 'adminuser', 'action' => 'list', 'field' => 'admin_status', 'sort' => 'desc','module' => 'admin'), 'default', false); ?>">
											<img src="<?php echo $this->ADMIN_PATH; ?>img/datatables/sort_desc.png"  alt="Descending" title="Descending" class="sort_desc"  />
										</a>
									</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								<?php if (count($this->adminuserData) > 0): ?>
									<?php foreach ($this->adminuserData as $key => $value) : ?>
										<tr>
											<td>
											<?php //if ($value["admin_type"] == 0): ?>
												<input type="checkbox" class="content-checkbox chek_all" name="multicheck[]" value="<?php echo $value["admin_usr_id"]; ?>"/>&nbsp;
											<?php //endif; ?>
											<a href="<?php echo $this->url(array("module" => "admin","controller" => "adminuser", "action" => "form", "admin_usr_id" => $value["admin_usr_id"]), null, true); ?>"><?php echo $value["admin_firstname"]; ?> <?php echo $value["admin_lastname"]; ?></a></td>
											<td class="hidden-phone">
												<?php echo $value["admin_phone"]; ?>
											</td>
											<td class="hidden-phone">
												<?php echo $value["admin_email"]; ?>
											</td>
											<td class="hidden-phone">
												<?php if ($value["admin_type"] == 1): ?>
													<span class="label label-info label-mini">Super Admin</span>
												<?php else:?>
													<span class="label label-primary label-mini">Admin</span>
												<?php endif; ?>
											</td>
											<td>
											<?php if ($value["admin_status"] == 1): ?>
													<span class="label label-success label-mini">Active</span>
												<?php else:?>
													<span class="label label-warning label-mini">InActive</span>
												<?php endif; ?>
											</td>
											<td>
												<a title="Edit" class="btn btn-primary btn-xs" href="<?php echo $this->url(array("module" => "admin","controller" => "adminuser", "action" => "form", "admin_usr_id" => $value["admin_usr_id"]), null, true); ?>">
													<i class="fa fa-pencil"></i>
												</a>
												<a title="Delete" class="btn btn-danger btn-xs" href="<?php echo $this->url(array("module" => "admin","controller" => "adminuser", "action" => "delete", "admin_usr_id" => $value["admin_usr_id"]), null, true); ?>">
													<i class="fa fa-trash-o "></i>
												</a>
												<a title="View" class="btn btn-primary btn-xs" href="<?php echo $this->url(array("module" => "admin","controller" => "adminuser", "action" => "view", "admin_usr_id" => $value["admin_usr_id"]), null, true); ?>">
													<i class="fa fa-eye"></i>
												</a>
											</td>
										</tr>
									<?php endforeach; ?>
								<?php else: ?>
									<tr class="row2" >
										<td>&nbsp;</td>
										<td colspan="8"> No Record Found</td>
									</tr>
								<?php endif; ?>
							</tbody>
						</table>
					  
						<div class="panel-body">
							<div>
								<?php
									if (count($this->adminuserData) > 0):
										echo $this->paginator->displayPages();
									endif;
								?>
							</div>
						</div>				  
					</section>	
				</form>
			</div>
		</div>
		<!-- page end-->
	</section>
</section>
<!--main content end-->