<?php $this->headScript()->appendFile($this->JS_PATH . "user.js"); ?>
<div id="adminuser-listing"></div>
<?php $adminuser_model = $this->adminuseralldata; ?>
<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-lg-12">
                <div class="border-head">
                    <h3>Admin User Detail</h3>
                </div>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-lg-12">
                <section class="panel">
                    <div class="panel-body">
                        <div class="dd" id="nestable_list_1">
                            <ol class="dd-list">
								<div class="detail_label">Name: </div>
								<div class="dd-handle">
									<?php echo ucfirst($adminuser_model["admin_firstname"]); ?> <?php echo ucfirst($adminuser_model["admin_lastname"]); ?>
								</div>
                            </ol>
							<ol class="dd-list">
								<div class="detail_label">Phone: </div>
								<div class="dd-handle">
									<?php echo $adminuser_model["admin_phone"]; ?>
								</div>
                            </ol>
							<ol class="dd-list">
								<div class="detail_label">Email: </div>
								<div class="dd-handle">
									<?php echo $adminuser_model["admin_email"]; ?>
								</div>
                            </ol>
							<ol class="dd-list">
								<div class="detail_label">CreatedDate: </div>
								<div class="dd-handle">
									<?php echo $adminuser_model["admin_createddate"]; ?>
								</div>
                            </ol>
							<ol class="dd-list">
								<div class="detail_label">UpdatedDate: </div>
								<div class="dd-handle">
									<?php echo $adminuser_model["admin_updateddate"]; ?>
								</div>
                            </ol>
							<ol class="dd-list">
								<div class="detail_label">Type: </div>
								<div class="dd-handle">
									<?php echo ( $adminuser_model["admin_type"] == 1 ) ? "Super Admin" : "Admin"; ?>
								</div>
                            </ol>
							<ol class="dd-list">
								<div class="detail_label">Status: </div>
								<div class="dd-handle">
									 <?php echo ( $adminuser_model["admin_status"] == 1 ) ? "Active" : "Inactive"; ?>
								</div>
                            </ol>
                        </div>
                    </div>
                </section>
            </div>
        </div>
		<a class="btn btn-success btn-sm pull-left" href="<?php echo $this->url(array("module" => "admin", "controller" => "adminuser", "action" => "list"), null, TRUE); ?>">&nbsp;Back</a>
    </section>
</section>
<!--main content end-->
