<div class="inner-page-top clearfix">
    <h2 class="header-title"><?php echo $this->cmsData['c_title']; ?></h2>
</div><!-- end of inner-page-top -->
<div class="container-area clearfix">
    <div class="terms-container clearfix">
        <div class="container">
            <div class="row">
				<?php echo $this->cmsData['c_description']; ?>
            </div>
        </div>
    </div><!-- end of about-container -->
</div><!-- end of container-area -->